//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServvicesSoapClientcSharp.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="Service.BanqueWebService")]
    public interface BanqueWebService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWebService/conversionEuroToDirhamRequest", ReplyAction="http://service/BanqueWebService/conversionEuroToDirhamResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServvicesSoapClientcSharp.Service.conversionEuroToDirhamResponse conversionEuroToDirham(webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWebService/conversionEuroToDirhamRequest", ReplyAction="http://service/BanqueWebService/conversionEuroToDirhamResponse")]
        System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.conversionEuroToDirhamResponse> conversionEuroToDirhamAsync(webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWebService/getCompteRequest", ReplyAction="http://service/BanqueWebService/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServvicesSoapClientcSharp.Service.getCompteResponse getCompte(webServvicesSoapClientcSharp.Service.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWebService/getCompteRequest", ReplyAction="http://service/BanqueWebService/getCompteResponse")]
        System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.getCompteResponse> getCompteAsync(webServvicesSoapClientcSharp.Service.getCompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWebService/getComptesRequest", ReplyAction="http://service/BanqueWebService/getComptesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServvicesSoapClientcSharp.Service.getComptesResponse getComptes(webServvicesSoapClientcSharp.Service.getComptesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWebService/getComptesRequest", ReplyAction="http://service/BanqueWebService/getComptesResponse")]
        System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.getComptesResponse> getComptesAsync(webServvicesSoapClientcSharp.Service.getComptesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conversionEuroToDirham", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class conversionEuroToDirhamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double montant;
        
        public conversionEuroToDirhamRequest() {
        }
        
        public conversionEuroToDirhamRequest(double montant) {
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conversionEuroToDirhamResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class conversionEuroToDirhamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public conversionEuroToDirhamResponse() {
        }
        
        public conversionEuroToDirhamResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private bool codeFieldSpecified;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
                this.RaisePropertyChanged("codeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getCompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long code;
        
        public getCompteRequest() {
        }
        
        public getCompteRequest(long code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public webServvicesSoapClientcSharp.Service.compte @return;
        
        public getCompteResponse() {
        }
        
        public getCompteResponse(webServvicesSoapClientcSharp.Service.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptes", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getComptesRequest {
        
        public getComptesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptesResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getComptesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public webServvicesSoapClientcSharp.Service.compte[] @return;
        
        public getComptesResponse() {
        }
        
        public getComptesResponse(webServvicesSoapClientcSharp.Service.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueWebServiceChannel : webServvicesSoapClientcSharp.Service.BanqueWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueWebServiceClient : System.ServiceModel.ClientBase<webServvicesSoapClientcSharp.Service.BanqueWebService>, webServvicesSoapClientcSharp.Service.BanqueWebService {
        
        public BanqueWebServiceClient() {
        }
        
        public BanqueWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServvicesSoapClientcSharp.Service.conversionEuroToDirhamResponse webServvicesSoapClientcSharp.Service.BanqueWebService.conversionEuroToDirham(webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest request) {
            return base.Channel.conversionEuroToDirham(request);
        }
        
        public double conversionEuroToDirham(double montant) {
            webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest inValue = new webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest();
            inValue.montant = montant;
            webServvicesSoapClientcSharp.Service.conversionEuroToDirhamResponse retVal = ((webServvicesSoapClientcSharp.Service.BanqueWebService)(this)).conversionEuroToDirham(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.conversionEuroToDirhamResponse> webServvicesSoapClientcSharp.Service.BanqueWebService.conversionEuroToDirhamAsync(webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest request) {
            return base.Channel.conversionEuroToDirhamAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.conversionEuroToDirhamResponse> conversionEuroToDirhamAsync(double montant) {
            webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest inValue = new webServvicesSoapClientcSharp.Service.conversionEuroToDirhamRequest();
            inValue.montant = montant;
            return ((webServvicesSoapClientcSharp.Service.BanqueWebService)(this)).conversionEuroToDirhamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServvicesSoapClientcSharp.Service.getCompteResponse webServvicesSoapClientcSharp.Service.BanqueWebService.getCompte(webServvicesSoapClientcSharp.Service.getCompteRequest request) {
            return base.Channel.getCompte(request);
        }
        
        public webServvicesSoapClientcSharp.Service.compte getCompte(long code) {
            webServvicesSoapClientcSharp.Service.getCompteRequest inValue = new webServvicesSoapClientcSharp.Service.getCompteRequest();
            inValue.code = code;
            webServvicesSoapClientcSharp.Service.getCompteResponse retVal = ((webServvicesSoapClientcSharp.Service.BanqueWebService)(this)).getCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.getCompteResponse> webServvicesSoapClientcSharp.Service.BanqueWebService.getCompteAsync(webServvicesSoapClientcSharp.Service.getCompteRequest request) {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.getCompteResponse> getCompteAsync(long code) {
            webServvicesSoapClientcSharp.Service.getCompteRequest inValue = new webServvicesSoapClientcSharp.Service.getCompteRequest();
            inValue.code = code;
            return ((webServvicesSoapClientcSharp.Service.BanqueWebService)(this)).getCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServvicesSoapClientcSharp.Service.getComptesResponse webServvicesSoapClientcSharp.Service.BanqueWebService.getComptes(webServvicesSoapClientcSharp.Service.getComptesRequest request) {
            return base.Channel.getComptes(request);
        }
        
        public webServvicesSoapClientcSharp.Service.compte[] getComptes() {
            webServvicesSoapClientcSharp.Service.getComptesRequest inValue = new webServvicesSoapClientcSharp.Service.getComptesRequest();
            webServvicesSoapClientcSharp.Service.getComptesResponse retVal = ((webServvicesSoapClientcSharp.Service.BanqueWebService)(this)).getComptes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.getComptesResponse> webServvicesSoapClientcSharp.Service.BanqueWebService.getComptesAsync(webServvicesSoapClientcSharp.Service.getComptesRequest request) {
            return base.Channel.getComptesAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServvicesSoapClientcSharp.Service.getComptesResponse> getComptesAsync() {
            webServvicesSoapClientcSharp.Service.getComptesRequest inValue = new webServvicesSoapClientcSharp.Service.getComptesRequest();
            return ((webServvicesSoapClientcSharp.Service.BanqueWebService)(this)).getComptesAsync(inValue);
        }
    }
}
