
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BanqueWebServiceService", targetNamespace = "http://service/", wsdlLocation = "http://192.168.10.1:8585/BWS?wsdl")
public class BanqueWebServiceService
    extends Service
{

    private final static URL BANQUEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BANQUEWEBSERVICESERVICE_EXCEPTION;
    private final static QName BANQUEWEBSERVICESERVICE_QNAME = new QName("http://service/", "BanqueWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.1:8585/BWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUEWEBSERVICESERVICE_WSDL_LOCATION = url;
        BANQUEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public BanqueWebServiceService() {
        super(__getWsdlLocation(), BANQUEWEBSERVICESERVICE_QNAME);
    }

    public BanqueWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUEWEBSERVICESERVICE_QNAME, features);
    }

    public BanqueWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, BANQUEWEBSERVICESERVICE_QNAME);
    }

    public BanqueWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUEWEBSERVICESERVICE_QNAME, features);
    }

    public BanqueWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueWebService
     */
    @WebEndpoint(name = "BanqueWebServicePort")
    public BanqueWebService getBanqueWebServicePort() {
        return super.getPort(new QName("http://service/", "BanqueWebServicePort"), BanqueWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueWebService
     */
    @WebEndpoint(name = "BanqueWebServicePort")
    public BanqueWebService getBanqueWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "BanqueWebServicePort"), BanqueWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw BANQUEWEBSERVICESERVICE_EXCEPTION;
        }
        return BANQUEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
