
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientWebService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientWebService {


    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "service.GetComptesResponse")
    @Action(input = "http://service/ClientWebService/getComptesRequest", output = "http://service/ClientWebService/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param nom
     * @return
     *     returns service.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClient", targetNamespace = "http://service/", className = "service.GetClient")
    @ResponseWrapper(localName = "getClientResponse", targetNamespace = "http://service/", className = "service.GetClientResponse")
    @Action(input = "http://service/ClientWebService/getClientRequest", output = "http://service/ClientWebService/getClientResponse")
    public Client getClient(
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

    /**
     * 
     * @param nom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertToLowcase", targetNamespace = "http://service/", className = "service.ConvertToLowcase")
    @ResponseWrapper(localName = "convertToLowcaseResponse", targetNamespace = "http://service/", className = "service.ConvertToLowcaseResponse")
    @Action(input = "http://service/ClientWebService/convertToLowcaseRequest", output = "http://service/ClientWebService/convertToLowcaseResponse")
    public String convertToLowcase(
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

}
